name: Test Connection

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Echo
        run: |
          echo "Hello GitHub Actions"
          echo "Current directory: $(pwd)"
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub sha: ${{ github.sha }}"
